namespace: gitea
domain: apps.domain.com

gitea:
  containerSecurityContext:
    runAsUser: 1000

  persistence:
    enabled: true
    size: 20Gi

  valkey-cluster:
    enabled: false
  valkey:
    enabled: true
    # Use legacy bitnami image until Gitea community finds better solution
    # https://gitea.com/gitea/helm-gitea/issues/903
    image:
      repository: bitnamilegacy/valkey
      tag: 8.1.3-debian-12-r3

  postgresql-ha:
    enabled: false
  postgresql:
    enabled: true
    image:
      repository: bitnamilegacy/postgresql
      tag: 17.6.0-debian-12-r4
